name: console_logger_pro_example
description: Example for console_logger_pro.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  console_logger_pro:
    path: ../
